kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker
  commands:
  - docker build -t myapp .

- name: deploy
  image: alpine
  environment:
    - DOCKER_HOST=tcp://docker:2375
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker pull myapp
  - docker stop myapp || true
  - docker rm myapp || true
  - docker run -d --name myapp -p 80:80 myapp
