language: node_js
node_js:
  - "10"
# cache:
#   directories:
#     - node_modules
before_install: rm -rf node_modules  
install: npm install
before_script: npm i lru-cache toml @vue/component-compiler-utils @babel/core vue-router

script: npm run build

deploy:
  api_key:
    secure: $REPO_TOKEN
  provider: pages
  local_dir: ./docs/.vuepress/dist
  skip_cleanup: true
  github_token: $REPO_TOKEN
  keep_history: true
  on:
    branch: master
