language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
    
install: npm install
before_script: npm i @babel/core@^7.0.0-0

script: npm run build

deploy:
  api_key:
    secure: $REPO_TOKEN
  provider: pages
  local_dir: ./docs/.vuepress/dist
  skip_cleanup: true
  github_token: $REPO_TOKEN
  keep_history: true
  on:
    branch: master
