language: node_js
node_js:
  - "8"
install: npm i -g
install: npm i vuepress-theme-ououe -D

script: npm run build

deploy:
  api_key:
    secure: $REPO_TOKEN
  provider: pages
  local_dir: ./docs/.vuepress/dist
  skip_cleanup: true
  github_token: $REPO_TOKEN
  keep_history: true
  on:
    branch: master
